name: CI

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["**"]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.2"
          - "3.3"
          - "3.4"
        rails:
          - "7.2"
          - "8.0"
          - "8.1"
        database_url:
          - sqlite3:test_db
    env:
      RAILS_VERSION: ${{ matrix.rails }}
      DATABASE_URL: ${{ matrix.database_url }}
    name: Ruby ${{ matrix.ruby }} Rails ${{ matrix.rails }} DB ${{ matrix.database_url }}
    steps:
      - uses: actions/checkout@v7
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake test
