name: CI

on:
  push:
    branches: [ 'develop' ]
  pull_request:
    branches: ['**']

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.3'
          - '3.2'
        rails:
          - '7.1'
          - '7.2'
        database_url:
          - sqlite3:test_db
    env:
      RAILS_VERSION: ${{ matrix.rails }}
      DATABASE_URL: ${{ matrix.database_url }}
    name: Ruby ${{ matrix.ruby }} Rails ${{ matrix.rails }} DB ${{ matrix.database_url }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake test
